pluton.endpoint.controllers:
  -
    controller: CreateEndpoint
    route: endpoints:create
    url: /endpoint/create/
  -
    controller: ShowEndpoint
    route: endpoints:show
    url: /endpoint/{endpoint_id:\d+}/
  -
    controller: ConfigureEndpoint
    route: endpoints:configure
    url: /endpoint/{endpoint_id:\d+}/configure/
